version: 2
updates:
  - package-ecosystem: 'bun'
    directory: '/'
    schedule:
      interval: weekly
    commit-message:
      prefix: 'bump'
    groups:
      bun-dependencies:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    commit-message:
      prefix: 'bump'
    groups:
      npm-dependencies:
        patterns:
          - '*'

  - package-ecosystem: 'github-actions'
    directory: '.github/'
    schedule:
      interval: weekly
    commit-message:
      prefix: 'bump'
    groups:
      github-actions-dependencies:
        patterns:
          - '*'

  - package-ecosystem: 'uv'
    directory: 'scripts'
    schedule:
      interval: weekly
    commit-message:
      prefix: 'bump'
    groups:
      uv-dependencies:
        patterns:
          - '*'

  - package-ecosystem: 'pip'
    directory: 'scripts'
    schedule:
      interval: weekly
    commit-message:
      prefix: 'bump'
    groups:
      pip-dependencies:
        patterns:
          - '*'
