version: 2
updates:
  - package-ecosystem: "bun" 
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-action"
    directory: "/"
    schedule:
      interval: "weekly"
