version: 2
updates:
  - package-ecosystem: 'bun'
    directory: '/'
    schedule:
      interval: weekly
    commit-message:
      prefix: 'bump'
    groups:
      bun-dependencies:
        patterns:
          - '*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: weekly
    commit-message:
      prefix: 'bump'
    groups:
      github-actions-dependencies:
        patterns:
          - '*'
